# -*- coding: utf-8 -*-
"""为拼图项目生成 Quartus 工程文件（qpf + qsf）。

下面的引脚表**照抄自开发板手册**
（MAXII数字实验板（LCM12864液晶版）.pdf）。把它集中在一个脚本里，
就意味着开发板手册是引脚映射的唯一来源，每个生成的 .qsf 都能与它逐条比对，
而不必把引脚手工敲进工程文件。

用法：
    python scripts/gen_project.py                 # top = board_test_top
    python scripts/gen_project.py puzzle_top      # top = puzzle_top（推荐）

⚠️ 本脚本**可以在任意目录、任意克隆位置运行**：仓库根由 `__file__` 推出，
   生成的文件一定落在**你自己克隆出来的** `quartus/` 下，不会写去别的地方。
"""
import re, sys, pathlib

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# 仓库根 = 本脚本所在目录（scripts/）的上一级。
# ⚠️ 这里**绝不能写死绝对路径**：同学把仓库克隆到别的目录后，
#    写死的 ROOT 会让他机器上"凭空新建"出作者的那条路径，
#    而他自己仓库里的 quartus/puzzle.qpf 始终不存在 ——
#    最坏的地方是它**不报错、退出码还是 0**，根本看不出来。
ROOT = pathlib.Path(__file__).resolve().parent.parent
# Quartus 工程位于 quartus/（旧目录布局）。把生成的文件集中放在
# 这一个子目录里，一份全新 clone 出来的仓库就能直接编译，
# 无需任何手工建工程的步骤。
PROJ = ROOT / "quartus"
DEVICE = "EPM1270T144C5"
FAMILY = "MAX II"

# --- 开发板手册引脚表 -------------------------------------------------
PINS = {
    "clk": 18,
    "sw7": 125,
    # 4x4 矩阵键盘
    "kp_col": [117, 118, 119, 120],
    "kp_row": [111, 112, 113, 114],
    # 点阵：行低电平有效、列高电平有效
    "dot_row": [8, 7, 6, 5, 4, 3, 2, 1],
    "dot_colr": [22, 21, 16, 15, 14, 13, 12, 11],
    "dot_colg": [45, 44, 43, 42, 41, 40, 39, 38],
    # 数码管：先 AA..AP、再 CAT0..CAT7
    "seg": [62, 59, 58, 57, 55, 53, 52, 51],
    "cat": [63, 66, 67, 68, 69, 70, 30, 31],
    # 蜂鸣器与复位按键
    "buzz": 60,
    "btn": 61,
}

# 每个顶层实际拥有哪些端口
#   注意：'btn'（BTN0、PIN_61）必须在此列出。漏掉它并不是
#   无害的疏忽：布局布线器会把这个未约束的输入悄悄放到任意空闲引脚上，
#   于是复位键根本不工作，唯一的线索只有
#   "No exact pin location assignment(s) for 1 pins of 52 total pins"。
TOP_PORTS = {
    "board_test_top": ["clk", "sw7", "btn", "kp_row", "kp_col", "dot_row",
                       "dot_colr", "dot_colg", "seg", "cat", "buzz"],
    "puzzle_top":     ["clk", "sw7", "btn", "kp_row", "kp_col", "dot_row",
                       "dot_colr", "dot_colg", "seg", "cat", "buzz"],
    # 纯显示测试不使用键盘
    "disp_test_top":  ["clk", "sw7", "dot_row", "dot_colr", "dot_colg", "seg", "cat"],
    "keypad_diag_top": ["clk", "sw7", "btn", "kp_row", "kp_col",
                        "dot_row", "dot_colr", "dot_colg", "seg", "cat", "buzz"],
    # 注意：kp_row / kp_col 必须列出。漏掉它们不会被下面的
    # 「端口无引脚」检查捕获（那道检查只看你确实列出的端口），
    # 于是键盘引脚会悄悄变成未约束，布局布线器把它们
    # 散落到任意空闲引脚上 —— 看起来与硬件损坏一模一样。
    "keypad_raw_top": ["clk", "sw7", "btn", "kp_row", "kp_col",
                       "dot_row", "dot_colr", "dot_colg", "seg", "cat"],
}

def qsf(top: str) -> str:
    L = []
    # 注意：Quartus II 9.1 的 .qsf 文件用 '#' 作注释。'--' 是 VHDL 的
    # 写法，会让 Quartus 读不了这个设置文件（"Error reading
    # Quartus II Settings File ... line 1"）。保留 '#'。
    L.append("# ============================================================")
    L.append("#  puzzle.qsf -- Quartus II 9.1 project settings")
    L.append("#  GENERATED BY scripts/gen_project.py -- do not hand-edit pins.")
    L.append("#  Pin numbers come from the board manual; they are NOT guesses.")
    L.append("# ============================================================")
    L.append("")
    L.append("set_global_assignment -name FAMILY \"%s\"" % FAMILY)
    L.append("set_global_assignment -name DEVICE %s" % DEVICE)
    L.append("set_global_assignment -name TOP_LEVEL_ENTITY %s" % top)
    L.append("set_global_assignment -name ORIGINAL_QUARTUS_VERSION 9.1")
    L.append("set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files")
    L.append("")
    L.append("# ---------------- source files ----------------")
    for f in ["puzzle_pkg.vhd", "clk_gen.vhd", "keypad_scan.vhd", "seg_scan.vhd",
              "dot_matrix_scan.vhd", "pattern_rom.vhd", "piece_rom.vhd",
              "rng_lfsr.vhd", "puzzle_ctrl.vhd", "disp_format.vhd",
              "game_fsm.vhd", "buzzer_ctrl.vhd",
              "puzzle_top.vhd", "board_test_top.vhd", "keypad_diag_top.vhd",
              "keypad_raw_top.vhd"]:
        L.append("set_global_assignment -name VHDL_FILE ../rtl/%s" % f)
    L.append("")
    L.append("# ---------------- timing ----------------")
    L.append("set_global_assignment -name SDC_FILE puzzle.sdc")
    L.append("")
    L.append("# ---------------- device options ----------------")
    L.append("set_global_assignment -name DEVICE_FILTER_PACKAGE TQFP")
    L.append("set_global_assignment -name DEVICE_FILTER_PIN_COUNT 144")
    # 注意：不要在此添加 ENABLE_CONFIGURATION_PINS —— Quartus II 9.1
    # 对 MAX II 拒绝这个赋值名（"Error reading Quartus II Settings File"）。
    L.append("# unused pins: keep them high-Z so the LCD / PS2 / VGA pins do not fight")
    L.append("set_global_assignment -name RESERVE_ALL_UNUSED_PINS \"AS INPUT TRI-STATED\"")
    # ERR-033（2026-10-09 第 11 工作阶段）：**打开资源复用**。
    #   渲染器（每拍算一行）与重叠检查引擎用的是同一套 row_mask/srl8 逻辑，
    #   但它们在两个进程里 → 综合器默认不合并。实测（同一份 RTL，只差这一行）：
    #     面积 1254 → **1190 LE（−64）**（配合两拍流水后 1199 → **1200 LE**、
    #     Fmax 44.97 → **51.44 MHz**）；不打开时这条设置默认 Off（见 map.rpt）。
    L.append("set_global_assignment -name AUTO_RESOURCE_SHARING ON")
    # ⚠️ 2026-10-09 第 16 工作阶段第二轮（乐句改成连奏/legato 填音之后重新扫描）：
    #   连奏版本整机 **1264 LE**（比"照抄休止"的 1269 少 5 LE —— 填音后旋律表里
    #   很多项变成相同/可合并的常量，布局器更容易塞），可装进 127 LAB 的种子也变了：
    #   **SEED 1 / 5 / 7 / 9 / 13 / 15** 都能装下，其中 **seed 5 的 Fmax 最高（53.28 MHz）**，
    #   seed 13 = 52.25、seed 1 = 52.13（seed 7 = 49.19、9 = 49.55 不满足 50 MHz）。
    #   ⚠️ **教训（本轮第三次踩到）**：器件瓶颈是 **127 个 LAB**，"哪些种子能装下 + 时序够"
    #   完全取决于当前 RTL —— 这次连**只改常量**（休止→连奏）都把结论翻了一遍。
    #   所以**每次动 RTL（哪怕只动常量）都要重扫种子并清洁重编译**。
    #
    # ⭐ 2026-10-10 **ERR-051 修法**（`game_fsm` 的自检窗口改数 8 个 tick_4hz、复用 `cnt`
    #   倒计数）之后**第四次重扫 1~16**（`.tmp/opt/seed_scan_err051.py`，判据同样是
    #   "装得进 127 LAB **且** Fmax ≥ 50 MHz"）：
    #     装得下：1/2/5/6/7/8/9/10/11/13/14/16（**3/4/12/15 装不下**）；
    #     其中**同时满足 50 MHz 的只有 1 / 10 / 14 / 16**：
    #       1 → **53.76 MHz**、14 → 51.90、10 → 51.66、16 → 50.67
    #       （5 = 48.58、2 = 49.38、6 = 48.76、7 = 49.30、9 = 49.80、8 = 47.71、13 = 46.08 不达标）
    #     ⇒ 取 **SEED 1（53.76 MHz）**。顺带：修法本身把面积从 1264 降到 **1263 LE**
    #       （删掉了原来 2 位的 `selfc` 计数器），Fmax 也从 53.28 提到 **53.76 MHz**。
    #     ⚠️ 再次印证："能装下"与"能用"是两个判据，必须一起看（ERR-050 的教训）。
    #
    # ⭐⭐ 2026-10-10 **第 18 工作阶段**（删按键音效 + 音效区分度重做 + 倒计时幽灵提示 +
    #    第三关限时 40→60 s）之后**第五次重扫 1~16**（`.tmp/opt/seed_scan_diff.py`）：
    #     装得下：**4 / 5 / 6 / 7 / 11 / 13 / 14 / 15 / 16**（1/2/3/8/9/10/12 装不下）；
    #     其中**同时满足 50 MHz 的**：**15 → 53.41**、14 → 52.86、11 → 52.11、
    #       5 → 51.49、6 → 50.91、16 → 50.61、13 → 50.40（4 = 48.21、7 = 49.74 不达标）
    #     ⇒ 当时取 **SEED 15（53.41 MHz）**。
    #    ⚠️ 本轮面积账（第 18 工作阶段）：
    #       删掉【确认】/【旋转】两个查表臂 **−9 LE**（1263 → 1254）→
    #       新增"倒计时幽灵提示" **+12 LE**（→ 1266）→
    #       再修"换音追赶"（`cnt` 换步清零，见 `docs/06` §19.8b）**+2 LE**（→ **1268**）。
    #
    # ⭐⭐ **第六次重扫 1~16**（`.tmp/opt/seed_scan_v18c.py`，判据同样是"装得进 127 LAB
    #    **且** ≥ 50 MHz"）：装得下 **1 / 2 / 4 / 6 / 7 / 8 / 12**
    #    （3/5/9/10/11/13/14/15/16 装不下）；同时达标的：**6 → 52.25**、4 → 51.54、
    #    2 → 50.49、8 → 50.27、1 → 50.20、7 → 50.01（12 = 48.37 不达标）
    #    ⇒ 取 **SEED 6（52.25 MHz）**。
    #    ⚠️ 另有一个"`cnt` 换步清零写成**独立 elsif**"的版本：面积 **1270 LE（零余量）**、
    #       最好 53.35 MHz。**最终取"并进外层条件"的 1268 LE / 52.25 MHz** ——
    #       宁可少 1.1 MHz，也要留 **2 个 LE 的余量**（1270/1270 时任何改动都装不下）。
    L.append("set_global_assignment -name SEED 6")
    L.append("")
    L.append("# ---------------- pins ----------------")

    def one(sig, pin):
        L.append("set_location_assignment PIN_%d -to %s" % (pin, sig))

    ports = TOP_PORTS[top]
    for sig in ["clk", "sw7", "btn", "buzz"]:
        if sig in ports:
            one(sig, PINS[sig])
    for group in ["kp_row", "kp_col", "dot_row", "dot_colr", "dot_colg", "seg", "cat"]:
        if group in ports:
            for i, p in enumerate(PINS[group]):
                one("%s[%d]" % (group, i), p)

    L.append("")
    return "\n".join(L) + "\n"

def qpf(top: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        '<!DOCTYPE project SYSTEM "..\\bin\\project.dtd">\n'
        '<project>\n'
        '\t<header>\n'
        '\t\t<fileVersion version="1" />\n'
        '\t</header>\n'
        '\t<project>\n'
        '\t\t<name>puzzle</name>\n'
        '\t\t<revision name="puzzle" />\n'
        '\t</project>\n'
        '</project>\n'
    )


def parse_entity_ports(top: str):
    """返回 rtl/<top>.vhd 的实体所声明的端口名。

    必须**先**剥掉注释。否则 "entity <name> is port ("
    这个模式会在诸如 "-- PIN_61, BTN0 reset" 的注释里
    命中，于是从错误的位置读取端口子句，使检查报告的
    端口少于实体实际拥有的 —— 一个悄悄少报的检查
    比完全没有检查更糟。
    """
    src = ROOT / "rtl" / (top + ".vhd")
    if not src.exists():
        raise SystemExit("top-level source not found: %s" % src)

    raw = src.read_text(encoding="utf-8", errors="replace")
    # 剥掉行注释（本项目的 RTL 不使用块注释）
    text = "\n".join(line.split("--")[0] for line in raw.splitlines())

    m = re.search(r"entity\s+\w+\s+is\s+port\s*\(", text, re.I)
    if not m:
        raise SystemExit("could not locate an entity port clause in %s" % src)

    # 走到端口子句的配对右括号
    depth = 1
    i = m.end()
    while i < len(text) and depth > 0:
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
        i += 1
    clause = text[m.end():i - 1]

    ports = []
    for part in clause.split(";"):
        mm = re.match(r"\s*([A-Za-z_]\w*)\s*:", part)
        if mm:
            ports.append(mm.group(1).lower())
    if not ports:
        raise SystemExit("no ports parsed from %s -- the guard cannot be trusted" % src)
    return ports


if __name__ == "__main__":
    top = sys.argv[1] if len(sys.argv) > 1 else "board_test_top"
    if top not in TOP_PORTS:
        raise SystemExit("unknown top: %s (known: %s)" % (top, list(TOP_PORTS)))
    # ---- 检查 0：确认自己确实跑在一个**完整的克隆**里 ------------------
    #   少了这一条，"克隆不完整/跑错目录"会退化成一个看不懂的报错
    #   （或者更糟：生成到别处去）。这里提前给出可操作的中文提示。
    if not (ROOT / "rtl").is_dir():
        raise SystemExit(
            "✗ 在 %s 下找不到 rtl/ 目录 —— 本脚本必须放在仓库的 scripts/ 里运行。\n"
            "  正确用法（在仓库根目录）： python scripts/gen_project.py %s" % (ROOT, top))
    src = ROOT / "rtl" / (top + ".vhd")
    if not src.is_file():
        raise SystemExit("✗ 找不到顶层源文件 %s —— 顶层实体名写错了吗？" % src)

    # ---- 检查 1：每个列出的端口都必须有引脚 ------------------------
    missing = [p for p in TOP_PORTS[top] if p not in PINS]
    if missing:
        raise SystemExit("no pin defined for port(s): %s" % missing)

    # ---- 检查 2：实体的每个端口都必须列出
    # 检查 1 看不到仅仅被漏写在 TOP_PORTS 里的端口，而正是这种
    # 遗漏让引脚变成未约束（布局布线器随后把它们散落到空闲引脚上，
    # 外设便悄悄永远不工作）。
    entity_ports = parse_entity_ports(top)
    unlisted = [q for q in entity_ports if q not in TOP_PORTS[top]]
    if unlisted:
        raise SystemExit(
            "top %s has port(s) %s that are NOT in TOP_PORTS[%s] -- they would "
            "be left unconstrained and placed on arbitrary pins."
            % (top, unlisted, top)
        )
    PROJ.mkdir(parents=True, exist_ok=True)
    # 先说要写什么、写到哪里 —— 幂等重跑时这一行能让人一眼确认"位置对不对"。
    print("将写入（仓库根 = %s）：" % ROOT)
    print("  · %s" % (PROJ / "puzzle.qpf"))
    print("  · %s" % (PROJ / "puzzle.qsf"))
    # ⚠️ newline="\n" 是必须的：Windows 上 write_text 默认写 CRLF，而
    #    .gitattributes 规定仓库内文本一律 LF —— 不统一的话每台机器上
    #    `git status` 都会因为换行符抖动而显示"文件被修改"（假 diff）。
    (PROJ / "puzzle.qpf").write_text(qpf(top), encoding="ascii", newline="\n")
    (PROJ / "puzzle.qsf").write_text(qsf(top), encoding="ascii", newline="\n")
    n = sum(len(PINS[g]) if isinstance(PINS[g], list) else 1
            for g in TOP_PORTS[top])
    print("wrote quartus/puzzle.qpf and quartus/puzzle.qsf  (top=%s, %d pins)" % (top, n))
    print()
    print("下一步：")
    print("  1) 用 Quartus II 9.1 打开 %s" % (PROJ / "puzzle.qpf"))
    print("  2) Start Compilation（或 & \"$env:QUARTUS_ROOT\\quartus\\bin\\quartus_sh.exe\" -t scripts/build.tcl）")
    print("  3) 烧录 %s" % (PROJ / "output_files" / "puzzle.pof"))
