# -*- coding: utf-8 -*-
"""Generate the Quartus project files (qpf + qsf) for the puzzle project.

The pin table below is transcribed FROM THE BOARD MANUAL
(MAXII数字实验板（LCM12864液晶版）.pdf).  Keeping it in one script means the
board manual is the single source of the pin map and every generated .qsf can be
diffed against it, instead of pins being hand-typed into the project file.

Usage:
    python scripts/gen_project.py                 # top = board_test_top
    python scripts/gen_project.py puzzle_top      # top = puzzle_top
"""
import re, sys, pathlib

ROOT = pathlib.Path(r"C:\Users\sznnn\Desktop\dld")
# The Quartus project lives in quartus/ (the old layout).  Keeping the
# generated files in one sub-directory means a fresh clone can be built without
# any manual project creation step.
PROJ = ROOT / "quartus"
DEVICE = "EPM1270T144C5"
FAMILY = "MAX II"

# --- board manual pin table -------------------------------------------------
PINS = {
    "clk": 18,
    "sw7": 125,
    # 4x4 matrix keypad
    "kp_col": [117, 118, 119, 120],
    "kp_row": [111, 112, 113, 114],
    # dot matrix : rows active LOW, columns active HIGH
    "dot_row": [8, 7, 6, 5, 4, 3, 2, 1],
    "dot_colr": [22, 21, 16, 15, 14, 13, 12, 11],
    "dot_colg": [45, 44, 43, 42, 41, 40, 39, 38],
    # seven-segment : AA..AP then CAT0..CAT7
    "seg": [62, 59, 58, 57, 55, 53, 52, 51],
    "cat": [63, 66, 67, 68, 69, 70, 30, 31],
    # buzzer and reset button
    "buzz": 60,
    "btn": 61,
}

# which ports each top level actually has
#   NOTE: 'btn' (BTN0, PIN_61) must be listed here.  Leaving it out is not a
#   harmless omission: the fitter silently places the unconstrained input on an
#   arbitrary free pin, so the reset key simply does not work and the only clue
#   is "No exact pin location assignment(s) for 1 pins of 52 total pins".
TOP_PORTS = {
    "board_test_top": ["clk", "sw7", "btn", "kp_row", "kp_col", "dot_row",
                       "dot_colr", "dot_colg", "seg", "cat", "buzz"],
    "puzzle_top":     ["clk", "sw7", "btn", "kp_row", "kp_col", "dot_row",
                       "dot_colr", "dot_colg", "seg", "cat", "buzz"],
    # a pure display test uses no keypad
    "disp_test_top":  ["clk", "sw7", "dot_row", "dot_colr", "dot_colg", "seg", "cat"],
    "keypad_diag_top": ["clk", "sw7", "btn", "kp_row", "kp_col",
                        "dot_row", "dot_colr", "dot_colg", "seg", "cat", "buzz"],
    # NOTE: kp_row / kp_col MUST be listed.  Omitting them is not caught by the
    # "port has no pin" guard below (that guard only sees the ports you DID list),
    # so the keypad pins silently end up unconstrained and the fitter scatters
    # them over arbitrary free pins -- which looks exactly like broken hardware.
    "keypad_raw_top": ["clk", "sw7", "btn", "kp_row", "kp_col",
                       "dot_row", "dot_colr", "dot_colg", "seg", "cat"],
}

def qsf(top: str) -> str:
    L = []
    # NOTE: Quartus II 9.1 .qsf files use '#' for comments.  The '--' style is
    # VHDL and makes the settings file unreadable to Quartus ("Error reading
    # Quartus II Settings File ... line 1").  Keep '#'.
    L.append("# ============================================================")
    L.append("#  puzzle.qsf -- Quartus II 9.1 project settings")
    L.append("#  GENERATED BY scripts/gen_project.py -- do not hand-edit pins.")
    L.append("#  Pin numbers come from the board manual; they are NOT guesses.")
    L.append("# ============================================================")
    L.append("")
    L.append("set_global_assignment -name FAMILY \"%s\"" % FAMILY)
    L.append("set_global_assignment -name DEVICE %s" % DEVICE)
    L.append("set_global_assignment -name TOP_LEVEL_ENTITY %s" % top)
    L.append("set_global_assignment -name ORIGINAL_QUARTUS_VERSION 9.1")
    L.append("set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files")
    L.append("")
    L.append("# ---------------- source files ----------------")
    for f in ["puzzle_pkg.vhd", "clk_gen.vhd", "keypad_scan.vhd", "seg_scan.vhd",
              "dot_matrix_scan.vhd", "pattern_rom.vhd", "piece_rom.vhd",
              "rng_lfsr.vhd", "puzzle_ctrl.vhd", "disp_format.vhd",
              "game_fsm.vhd", "buzzer_ctrl.vhd",
              "puzzle_top.vhd", "board_test_top.vhd", "keypad_diag_top.vhd",
              "keypad_raw_top.vhd"]:
        L.append("set_global_assignment -name VHDL_FILE ../rtl/%s" % f)
    L.append("")
    L.append("# ---------------- timing ----------------")
    L.append("set_global_assignment -name SDC_FILE puzzle.sdc")
    L.append("")
    L.append("# ---------------- device options ----------------")
    L.append("set_global_assignment -name DEVICE_FILTER_PACKAGE TQFP")
    L.append("set_global_assignment -name DEVICE_FILTER_PIN_COUNT 144")
    # NOTE: do NOT add ENABLE_CONFIGURATION_PINS here -- Quartus II 9.1 rejects
    # that assignment name for MAX II ("Error reading Quartus II Settings File").
    L.append("# unused pins: keep them high-Z so the LCD / PS2 / VGA pins do not fight")
    L.append("set_global_assignment -name RESERVE_ALL_UNUSED_PINS \"AS INPUT TRI-STATED\"")
    # ERR-033（2026-10-09 第 11 工作阶段）：**打开资源复用**。
    #   渲染器（每拍算一行）与重叠检查引擎用的是同一套 row_mask/srl8 逻辑，
    #   但它们在两个进程里 → 综合器默认不合并。实测（同一份 RTL，只差这一行）：
    #     面积 1254 → **1190 LE（−64）**（配合两拍流水后 1199 → **1200 LE**、
    #     Fmax 44.97 → **51.44 MHz**）；不打开时这条设置默认 Off（见 map.rpt）。
    L.append("set_global_assignment -name AUTO_RESOURCE_SHARING ON")
    L.append("")
    L.append("# ---------------- pins ----------------")

    def one(sig, pin):
        L.append("set_location_assignment PIN_%d -to %s" % (pin, sig))

    ports = TOP_PORTS[top]
    for sig in ["clk", "sw7", "btn", "buzz"]:
        if sig in ports:
            one(sig, PINS[sig])
    for group in ["kp_row", "kp_col", "dot_row", "dot_colr", "dot_colg", "seg", "cat"]:
        if group in ports:
            for i, p in enumerate(PINS[group]):
                one("%s[%d]" % (group, i), p)

    L.append("")
    return "\n".join(L) + "\n"

def qpf(top: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        '<!DOCTYPE project SYSTEM "..\\bin\\project.dtd">\n'
        '<project>\n'
        '\t<header>\n'
        '\t\t<fileVersion version="1" />\n'
        '\t</header>\n'
        '\t<project>\n'
        '\t\t<name>puzzle</name>\n'
        '\t\t<revision name="puzzle" />\n'
        '\t</project>\n'
        '</project>\n'
    )


def parse_entity_ports(top: str):
    """Return the port names declared by the entity of rtl/<top>.vhd.

    Comments are stripped FIRST.  Without that, the pattern
    "entity <name> is port (" matches inside a comment such as
    "-- PIN_61, BTN0 reset" and the clause is read from the wrong place, which
    makes the guard report fewer ports than the entity really has -- a guard that
    silently under-reports is worse than no guard at all.
    """
    src = ROOT / "rtl" / (top + ".vhd")
    if not src.exists():
        raise SystemExit("top-level source not found: %s" % src)

    raw = src.read_text(encoding="utf-8", errors="replace")
    # strip line comments (no block comments are used in this project's RTL)
    text = "\n".join(line.split("--")[0] for line in raw.splitlines())

    m = re.search(r"entity\s+\w+\s+is\s+port\s*\(", text, re.I)
    if not m:
        raise SystemExit("could not locate an entity port clause in %s" % src)

    # walk to the matching close paren of the port clause
    depth = 1
    i = m.end()
    while i < len(text) and depth > 0:
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
        i += 1
    clause = text[m.end():i - 1]

    ports = []
    for part in clause.split(";"):
        mm = re.match(r"\s*([A-Za-z_]\w*)\s*:", part)
        if mm:
            ports.append(mm.group(1).lower())
    if not ports:
        raise SystemExit("no ports parsed from %s -- the guard cannot be trusted" % src)
    return ports


if __name__ == "__main__":
    top = sys.argv[1] if len(sys.argv) > 1 else "board_test_top"
    if top not in TOP_PORTS:
        raise SystemExit("unknown top: %s (known: %s)" % (top, list(TOP_PORTS)))
    # ---- guard 1: every listed port must have a pin ------------------------
    missing = [p for p in TOP_PORTS[top] if p not in PINS]
    if missing:
        raise SystemExit("no pin defined for port(s): %s" % missing)

    # ---- guard 2: every port of the ENTITY must be listed -------------------
    # Guard 1 cannot see a port that was simply left out of TOP_PORTS, and that
    # omission is exactly what leaves pins unconstrained (the fitter then scatters
    # them over free pins and the peripheral silently never works).
    entity_ports = parse_entity_ports(top)
    unlisted = [q for q in entity_ports if q not in TOP_PORTS[top]]
    if unlisted:
        raise SystemExit(
            "top %s has port(s) %s that are NOT in TOP_PORTS[%s] -- they would "
            "be left unconstrained and placed on arbitrary pins."
            % (top, unlisted, top)
        )
    PROJ.mkdir(parents=True, exist_ok=True)
    # ⚠️ newline="\n" 是必须的：Windows 上 write_text 默认写 CRLF，而
    #    .gitattributes 规定仓库内文本一律 LF —— 不统一的话每台机器上
    #    `git status` 都会因为换行符抖动而显示"文件被修改"（假 diff）。
    (PROJ / "puzzle.qpf").write_text(qpf(top), encoding="ascii", newline="\n")
    (PROJ / "puzzle.qsf").write_text(qsf(top), encoding="ascii", newline="\n")
    n = sum(len(PINS[g]) if isinstance(PINS[g], list) else 1
            for g in TOP_PORTS[top])
    print("wrote quartus/puzzle.qpf and quartus/puzzle.qsf  (top=%s, %d pins)" % (top, n))
